# Generated by Django 5.2.17 on 2026-09-09 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_tag_product_preview_productphoto_product_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("running", "Выполняется"),
                            ("done", "Готов"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт",
                "verbose_name_plural": "Отчёты",
            },
        ),
    ]
