# Generated by Django 5.2.17 on 2026-09-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="ID задачи движка"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="product_price_gt_0"
            ),
        ),
    ]
