# Generated by Django 5.2.17 on 2026-09-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_report_task_id_product_product_price_gt_0"),
    ]

    operations = []
