# Generated by Django 5.2.17 on 2026-09-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_demoworkspace_productread_product_metadata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRead',
        ),
    ]
